### ISSUE TITLE
Returning a List<Type> from a Model

### ISSUE THREAD

**Issue by MaxMommersteeg** [pauldotknopf/Qml.Net#59]
I'm trying to build a small application that displays todo items in a qml view. To do this I want to return a 
`List<TodoItem>` from my model.

### Problem

I'm not able to iterate over the list using a for-loop. `console.log()` displays the following value: ```List`1(0x1c071c50b30)```.

I'm also not able to iterate over the list.

### Model

```csharp
public class TodoItemListModel
{
    private readonly List<TodoItem> _todoItems;

    public TodoItemListModel()
    {
        _todoItems = new List<TodoItem>
        {
            new TodoItem("Cleaning the house"),
            new TodoItem("Doing groceries"),
            new TodoItem("Getting a haircut")
        };
    }

    public List<TodoItem> GetTodoItems()
    {
        return _todoItems;
    }
}
```

### QML

```csharp
Page {
        ListView {
                model: listViewModel
                Component.onCompleted: {
                        var arrTodoItems = ctrl.getTodoItems()
                        console.log(arrTodoItems)
                        for (var i = 0; i < arrTodoItems.length; i++)
                        {
                                console.log(arrTodoItems[i])
                        }
                }
        }

        TodoItemListModel {
                id: model
        }
}
```

Not sure if this isn't supported yet or something that I'm doing incorrectly.

**Comment by pauldotknopf** [comment]
Yeah, this is a sore point at the moment. This is the next thing I'll be working on (#55).

Until then, create a method on your model to get an item from a list at an index.

```
pubic class Model
{
    public object GetItem(IList<object> list, int index)
    {
        return list[index]
    }
}
```

**Comment by MaxMommersteeg** [comment]
Alright, thanks for your explanation. Perhaps we can add some context of this issue to issue https://github.com/pauldotknopf/Qml.Net/issues/55?

**Comment by pauldotknopf** [comment]
There is a lot of moving parts to that issue, and I haven't had time to fully suss out the reqs.

I've been looking at it now, and I think the first thing to address is #31. I will likely have this done by this weekend.

**Comment by pauldotknopf** [comment]
This feature is completed.

See this commit for an example: https://github.com/pauldotknopf/Qml.Net.Examples/commit/551dd105c8bdef6e369fa7d058cddd9d2afccca5
