### ISSUE TITLE
Request for a logo?

### ISSUE THREAD

**Issue by pauldotknopf** [pauldotknopf/Qml.Net#60]
I'd love someone to contribute mockup a simple logo that we could use for an upcoming docs website.

**Comment by waf** [comment]
Just to kick it off, here's the Qt green shape, with the two-toned styling that's typical of .NET projects (see [the two-toned icons here](https://docs.microsoft.com/en-us/dotnet/))

One logo with the capitalization of this project (Qml.Net):
<img src="https://user-images.githubusercontent.com/97195/44296277-c4564a00-a2e5-11e8-94f4-d827bde32bec.png" width="200" />

and one with the more typical .NET uppercased:

<img src="https://user-images.githubusercontent.com/97195/44296281-d9cb7400-a2e5-11e8-83de-3bab462e1122.png" width="200" />

Editable SVGs: ([lowercase](http://files.fuqua.io/qml.net/Qml%20Net%20lowercase.svg), [uppercase](http://files.fuqua.io/qml.net/Qml%20NET%20uppercase.svg))

**Comment by pauldotknopf** [comment]
Perfect! I'm going to run with the second one.

Thanks a lot!

**Comment by pauldotknopf** [comment]
Every lib/service I used to try to convert this to a png failed in it's formatting. Think you could provide my some pngs?

**Comment by waf** [comment]
@pauldotknopf could be the embedded font causing issues. Here are some SVGs ([zip download](https://github.com/pauldotknopf/Qml.Net/files/2300061/Qml.NET-logos.zip)) produced by inkscape, so they should be more compatible:

- Editing / updating.
    - The earlier version, with the embedded font: `Qml.NET-source-sans-pro-embedded.svg`
    - A version without source-sans-pro embedded (requires [source-sans-pro](https://github.com/adobe-fonts/source-sans-pro) installed on the system) `Qml.NET-source-sans-pro-not-embedded.svg`
- Distribution:
    - Fonts converted to SVG paths, so no dependencies: `Qml.NET-paths.svg`
    - PNG versions, labeled by width in pixels: `Qml.NET-16w.png`, `Qml.NET-32w.png`, `Qml.NET-64w.png`, `Qml.NET-256w.png`, `Qml.NET-512w.png`

**Comment by pauldotknopf** [comment]
Bingo!

Thanks again!
