### ISSUE TITLE
Support for dependency injection in Models

### ISSUE THREAD

**Issue by MaxMommersteeg** [pauldotknopf/Qml.Net#63]
Currently working on a simple todo application (https://github.com/MaxMommersteeg/Qml.Net.TodoApp) and trying to use a repository in my model. I tend to use the `Models` (as seen in the examples) as my controller (like a controller in mvc). Creating a controller/model without a parameterless constructor throws a `System.MissingMethodException` exception.

I setup my dependency injection as follows:
### Program.cs
```csharp
 // Dependency injection.
var serviceCollection = new ServiceCollection();

var connectionStringBuilder = new SqliteConnectionStringBuilder { DataSource = "todoApp.db" };
var connectionString = connectionStringBuilder.ToString();

serviceCollection.AddDbContext<TodoAppDbContext>(options => options.UseSqlite(connectionString));
serviceCollection.AddSingleton<ITodoItemRepository, TodoItemRepository>();

var serviceProvider = serviceCollection.BuildServiceProvider();

serviceProvider.GetService<TodoAppDbContext>();

using (var dbContext = serviceProvider.GetService<TodoAppDbContext>())
{
    await dbContext.EnsureSeedData();
}
```

### TodoItemsController.cs
```csharp
public class TodoItemsController
{
    private readonly ITodoItemRepository _todoItemRepository;

    private IList<TodoItemModel> _todoItems = new List<TodoItemModel>();

    public TodoItemsController(ITodoItemRepository todoItemRepository)
    {
        _todoItemRepository = todoItemRepository;
    }

    [NotifySignal]
    public IList<TodoItemModel> TodoItems
    {
        get { return _todoItems; }
        private set { _todoItems = value; }
    }

    public async Task AddTodoItem(string title)
    {
        await _todoItemRepository.Add(new Core.Entities.TodoItem
            {
                Title = title,
            })
            .ConfigureAwait(false);

        await UpdateTodoItems()
            .ConfigureAwait(false);
    }

    public async Task MarkAsDone(int todoItemId)
    {
        var todoItem = await _todoItemRepository.Get(todoItemId)
            .ConfigureAwait(false);
        if (todoItem == null)
        {
            return;
        }

        todoItem.CompletedAt = DateTime.UtcNow;

        await _todoItemRepository.Update(todoItem)
            .ConfigureAwait(false);

        await UpdateTodoItems()
            .ConfigureAwait(false);
    }

    public async Task DeleteTodoItem(int todoItemId)
    {
        await _todoItemRepository.Delete(todoItemId)
            .ConfigureAwait(false);

        await UpdateTodoItems()
            .ConfigureAwait(false);
    }

    private async Task UpdateTodoItems()
    {
        _todoItems = (await _todoItemRepository.GetAll().ConfigureAwait(false)).ToModel();
        this.ActivateSignal("todoItemsChanged");
    }
}
```

### Exception

`System.MissingMethodException: 'No parameterless constructor defined for this object.'`

You can clone and run the `TodoApp.FrontEnd` project to reproduce the problem. Any ideas on how to handle dependency injection?

**Comment by pauldotknopf** [comment]
Set ```Qml.Net.TypeCreator.Current``` to your own implementation of ```ITypeCreator```.

**Comment by MaxMommersteeg** [comment]
Thanks, is there an example showing the intended use (registering an implementation to an interface.)?

**Comment by MaxMommersteeg** [comment]
Sadly to no avail. The `TodoAppDbContext` throws an `ObjectDisposedException`. Issue can be reproduced by starting the app and adding a todo item using the textfield and button.

Not sure whether `TodoAppDbContext` is setup correctly for dependency injection yet. The `ITodoItemRepository` is correctly injected into the `TodoItemsController` class.

### Program.cs
```csharp
public class Program
{
    public static async Task Main(string[] args)
    {
        // Dependency injection.
        var serviceCollection = new ServiceCollection();

        var connectionStringBuilder = new SqliteConnectionStringBuilder { DataSource = "todoApp.db" };
        var connectionString = connectionStringBuilder.ToString();

        serviceCollection.AddDbContext<TodoAppDbContext>(options => options.UseSqlite(connectionString));
        serviceCollection.AddSingleton<ITodoItemRepository, TodoItemRepository>();
        serviceCollection.AddSingleton<TodoItemsController>();

        var serviceProvider = serviceCollection.BuildServiceProvider();

        // Seed database.
        using (var dbContext = serviceProvider.GetService<TodoAppDbContext>())
        {
            await dbContext.EnsureSeedData().ConfigureAwait(false);
        }

        QQuickStyle.SetStyle("Material");

        using (var application = new QGuiApplication(args))
        {
            using (var qmlEngine = new QQmlApplicationEngine())
            {
                QQmlApplicationEngine.RegisterType<TodoItemsController>("TodoApp");

                TypeCreator.Current = TypeCreator.FromDelegate((type) => serviceProvider.GetRequiredService(type));

                qmlEngine.Load("Main.qml");

                application.Exec();
            }
        }
    }
}
```

**Comment by pauldotknopf** [comment]
Try making sure all your types are registered as a singleton.

**Comment by MaxMommersteeg** [comment]
I don't think making `TodoAppDbContext` a singleton would be a good practice.. Not sure how to continue from here. For sake of the example app I could write to a simple json file on desk I suppose.

**Comment by pauldotknopf** [comment]
When running desktop apps, scope practices are a little different that the per-request model of ASP.NET. I've seen (and used) a singleton model because there isn't a good location to create scope in desktop apps.

**Comment by MaxMommersteeg** [comment]
I agree with you. So the default `AddDbContext<TodoAppDbContext>()` method sets the lifetime to `Scoped`. I tried setting it to `singleton` manually: `serviceCollection.AddDbContext<TodoAppDbContext>(options => options.UseSqlite(connectionString), ServiceLifetime.Singleton);`. Sadly it is giving me the same exception. For some reason `TodoAppDbContext` is still disposed.

**Comment by MaxMommersteeg** [comment]
Stupid issue, totally my mistake:
```csharp
// Seed database.
using (var dbContext = serviceProvider.GetService<TodoAppDbContext>())
{
    await dbContext.EnsureSeedData().ConfigureAwait(false);
}
```

Above code was the problem. Setting `ServiceLifetime.Singleton` was correct, but retrieving the `TodoAppDbContext` in a using disposes (of course) the object after use. See current `Program.cs` in my repository for the working code.
