### ISSUE TITLE
OleInitialize() failed on startup. COM error.

### ISSUE THREAD

**Issue by MaxMommersteeg** [pauldotknopf/Qml.Net#65]
Starting an Qml.Net application shows following error in console:
>QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"

More information can be found [here](https://docs.microsoft.com/en-us/windows/desktop/api/combaseapi/nf-combaseapi-coinitializeex).

**Comment by pauldotknopf** [comment]
Yeah, this happens when running just a regular Qt/Qml app as well.

It doesn't harm anything.

**Comment by MaxMommersteeg** [comment]
I see, not sure whether to close this issue, or leave it be. Your call.

**Comment by eabase** [comment]
I get this error when I use matplotlib and pythonnet.

**Comment by vadi2** [comment]
Anyone worked out a way to suppress this?

**Comment by eabase** [comment]
Doesn't seem much is going on in this repo... Nothing since ~ 6 months now. :cry:

**Comment by roxf18** [comment]
hi please annotate main method by [STAThread]
