### ISSUE TITLE
Is it possible to use WebEngine?

### ISSUE THREAD

**Issue by TripleWhy** [pauldotknopf/Qml.Net#66]
I tried executing the QML code from this example: http://doc.qt.io/qt-5/qtwebengine-webengine-minimal-example.html
However without the code from the C++ part, it does not run:
```
//This is interesting, but not directly related to the WebEngine
QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);

//This is required:
QtWebEngine::initialize();
```

**Comment by pauldotknopf** [comment]
It is possible to use ```QtWebEngine```, but currently isn't wrapped for .NET.

We hand-craft our wrapping stuff (not auto-generated) so we generate .NET wrappers for things as needed.

I can definitely see this as "needed".

I am currently working on other tasks for Qml.Net at the moment, but I'd gladly accept a pull request.

If you are interested, here is a similar file that wraps a Qt static method: https://github.com/pauldotknopf/Qml.Net/blob/develop/src/native/QmlNet/QmlNet/qml/QQuickStyle.cpp

**Comment by ColinDuquesnoy** [comment]
Hi, 

I am trying to use QtWebEngine but I ran into the following issue:

```
Qml.Net wasn't compiled with webengine.
libpng warning: iCCP: known incorrect sRGB profile
QQmlComponent: Component is not ready
QObject::connect(QQuickWebEngineView, QWebEngineWebViewPrivate): invalid null parameter
QObject::connect(QQuickWebEngineView, QWebEngineWebViewPrivate): invalid null parameter
QObject::connect(QQuickWebEngineView, QWebEngineWebViewPrivate): invalid null parameter
QObject::connect(QQuickWebEngineView, QWebEngineWebViewPrivate): invalid null parameter
Process finished with exit code 11.
```

How do I build Qml.Net with webengine support? Why is webengine support not enabled by default?

**Comment by PlumpMath** [comment]
Is it possible now?
