### ISSUE TITLE
Is support Linux Arm  ?

### ISSUE THREAD

**Issue by seebosmile** [pauldotknopf/Qml.Net#69]
Is support Linux Arm  like Java+Qt Jambi  ?

**Comment by seebosmile** [comment]
Thanks ,  i will try on PI

**Comment by pauldotknopf** [comment]
Great.

Remember that our ```Qml.Net.LinuxBinaries``` is for x64 only. You'll have to manually compile the ```libQmlNet.so``` lib and make sure it is in ```LD_LIBRARY_PATH``` (or ```/usr/lib/```).

**Comment by deinok** [comment]
Can we add support to `linux-arm` to `Qml.Net.LinuxBinaries`?
